# OperaLinux Violin defaults.
REPOSITORY_URL="https://raw.githubusercontent.com/OperaLinux/void/main"
RELEASES_URL="https://raw.githubusercontent.com/OperaLinux/update/main"
DB_DIR="/var/lib/violin"
CACHE_DIR="/var/cache/violin"
LOG_FILE="/var/log/violin.log"
SYSTEM_LOG_FILE="/var/log/violin-system-upgrade.log"
SNAPSHOT_KEEP=3
